### ISSUE TITLE
(0.0/0.0).string is "NaN.0" in JS

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#736]
Given:

    print((0.0/0.0).string);

Ceylon JS prints:

    NaN.0

**Comment by FroMage** [comment]
Fixed.

**Comment by gavinking** [comment]
Thanks, but the same bug is still there for `infinity.string`.

**Comment by FroMage** [comment]
What, you mean you want _every_ number to print correctly? But floats are infinite, how can I test them _all_?

**Comment by gavinking** [comment]
> But floats are infinite

That's not true at all! There are only `2^64` tests you have to write!

Thanks :-)
